services:
  # 1. Le Serveur Backend + Frontend (Service Web)
  - type: web
    name: mining-autolog-app
    env: node
    plan: free
    # Commande pour tout installer et construire le frontend
    buildCommand: npm install && npm run build && cd server && npm install
    # Commande pour démarrer le serveur
    startCommand: cd server && node index_mysql.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: mining-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: mining-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: mining-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mining-db
          property: password
      - key: DB_PORT
        fromDatabase:
          name: mining-db
          property: port

databases:
  # 2. La Base de Données MySQL
  - name: mining-db
    databaseName: gestion_stock_db
    user: admin
    plan: free
